
export const quizData = [
  // SECTION 1: Grammar - Alternatives
  { id: 'g1_1', section: 'Grammar', task: '1 Choose the correct alternatives.', label: "1 What’s your [blank] name?", type: 'choice', options: ["friend’s", "friend"], correctAnswer: "friend’s", explanation: "Egalik shakli: Do'stingning ismi (Friend's name).", isExample: false },
  { id: 'g1_2', section: 'Grammar', task: '1 Choose the correct alternatives.', label: "2 I think [blank] a nice photo.", type: 'choice', options: ["it’s", "its"], correctAnswer: "it’s", explanation: "It is (It's) - Bu chiroyli rasm." },
  { id: 'g1_3', section: 'Grammar', task: '1 Choose the correct alternatives.', label: "3 [blank] phone is here.", type: 'choice', options: ["You’re", "Your"], correctAnswer: "Your", explanation: "Your - Sening telefoning. (You're - sen shundaysan)." },
  { id: 'g1_4', section: 'Grammar', task: '1 Choose the correct alternatives.', label: "4 Is [blank] brother a doctor?", type: 'choice', options: ["she", "her"], correctAnswer: "her", explanation: "Her - uning (ayol kishiga nisbatan egalik)." },
  { id: 'g1_5', section: 'Grammar', task: '1 Choose the correct alternatives.', label: "5 [blank] house is big.", type: 'choice', options: ["They’re", "Their"], correctAnswer: "Their", explanation: "Their - ularning uyi." },
  { id: 'g1_6', section: 'Grammar', task: '1 Choose the correct alternatives.', label: "6 This is [blank] friend, Claudia.", type: 'choice', options: ["we", "our"], correctAnswer: "our", explanation: "Our - bizning do'stimiz." },
  { id: 'g1_7', section: 'Grammar', task: '1 Choose the correct alternatives.', label: "7 My [blank] name is Toshi.", type: 'choice', options: ["brothers", "brother’s"], correctAnswer: "brother’s", explanation: "Aka/ukangning ismi (Brother's name)." },
  { id: 'g1_8', section: 'Grammar', task: '1 Choose the correct alternatives.', label: "8 [blank] from New York.", type: 'choice', options: ["His", "He’s"], correctAnswer: "He’s", explanation: "He is (He's) - U Nyu Yorkdan." },
  { id: 'g1_9', section: 'Grammar', task: '1 Choose the correct alternatives.', label: "9 Here is my cat. [blank] name is Tabby.", type: 'choice', options: ["It", "Its"], correctAnswer: "Its", explanation: "Its - uning (hayvon yoki narsaga nisbatan egalik)." },

  // SECTION 2: Grammar - Demonstratives (with Visual Hints)
  { id: 'g2_1', section: 'Grammar', task: '2 Complete the sentences with this, that, these or those.', label: "1 Is [blank] my book?", type: 'choice', options: ['this', 'that', 'these', 'those'], correctAnswer: 'this', visualHint: 'Near (Yaqin), 1 object', explanation: "Yaqindagi bitta narsa uchun 'this' ishlatiladi.", isExample: true },
  { id: 'g2_2', section: 'Grammar', task: '2 Complete the sentences with this, that, these or those.', label: "2 [blank] are your pens there.", type: 'choice', options: ['this', 'that', 'these', 'those'], correctAnswer: 'those', visualHint: 'Far (Uzoq), Plural (Ko‘plik)', explanation: "Uzoqdagi ko'p narsalar uchun 'those' ishlatiladi." },
  { id: 'g2_3', section: 'Grammar', task: '2 Complete the sentences with this, that, these or those.', label: "3 What’s in [blank] bag?", type: 'choice', options: ['this', 'that', 'these', 'those'], correctAnswer: 'this', visualHint: 'Near (Yaqin), 1 object', explanation: "Yaqindagi bitta narsa - this." },
  { id: 'g2_4', section: 'Grammar', task: '2 Complete the sentences with this, that, these or those.', label: "4 Are [blank] my keys?", type: 'choice', options: ['this', 'that', 'these', 'those'], correctAnswer: 'these', visualHint: 'Near (Yaqin), Plural (Ko‘plik)', explanation: "Yaqindagi ko'p narsalar uchun 'these' ishlatiladi." },
  { id: 'g2_5', section: 'Grammar', task: '2 Complete the sentences with this, that, these or those.', label: "5 Who are [blank] girls?", type: 'choice', options: ['this', 'that', 'these', 'those'], correctAnswer: 'those', visualHint: 'Far (Uzoq), Plural (Ko‘plik)', explanation: "Uzoqdagi ko'p odamlar/narsalar - those." },
  { id: 'g2_6', section: 'Grammar', task: '2 Complete the sentences with this, that, these or those.', label: "6 Who is [blank] boy?", type: 'choice', options: ['this', 'that', 'these', 'those'], correctAnswer: 'that', visualHint: 'Far (Uzoq), 1 object', explanation: "Uzoqdagi bitta shaxs - that." },

  // SECTION 3: Grammar - Writing Questions
  { id: 'g3_1', section: 'Grammar', task: '3 Write the questions to complete the conversations.', label: "1 A: [blank]? B: She’s my friend.", type: 'text-input', correctAnswer: "Who is she", explanation: "U kim? - Who is she?", isExample: true },
  { id: 'g3_2', section: 'Grammar', task: '3 Write the questions to complete the conversations.', label: "2 A: [blank]? B: Her name is Ana.", type: 'text-input', correctAnswer: "What's her name", explanation: "Uning ismi nima? - What is (What's) her name?" },
  { id: 'g3_3', section: 'Grammar', task: '3 Write the questions to complete the conversations.', label: "3 A: [blank]? B: She’s from Mexico.", type: 'text-input', correctAnswer: "Where is she from", explanation: "U qayerdan? - Where is she from?" },
  { id: 'g3_4', section: 'Grammar', task: '3 Write the questions to complete the conversations.', label: "4 A: [blank]? B: She’s 25.", type: 'text-input', correctAnswer: "How old is she", explanation: "U necha yoshda? - How old is she?" },
  { id: 'g3_5', section: 'Grammar', task: '3 Write the questions to complete the conversations.', label: "5 A: [blank]? B: Their names are Omer and Yusuf.", type: 'text-input', correctAnswer: "What are their names", explanation: "Ularning ismlari nima? - What are their names?" },
  { id: 'g3_6', section: 'Grammar', task: '3 Write the questions to complete the conversations.', label: "6 A: [blank]? B: They’re students.", type: 'text-input', correctAnswer: "What are they", explanation: "Ular kim (kasbi nima)? - What are they?" },
  { id: 'g3_7', section: 'Grammar', task: '3 Write the questions to complete the conversations.', label: "7 A: [blank]? B: They’re 21 and 23.", type: 'text-input', correctAnswer: "How old are they", explanation: "Ular necha yoshda? - How old are they?" },
  { id: 'g3_8', section: 'Grammar', task: '3 Write the questions to complete the conversations.', label: "8 A: [blank]? B: They’re from Ankara in Turkey.", type: 'text-input', correctAnswer: "Where are they from", explanation: "Ular qayerdan? - Where are they from?" },

  // SECTION 4: Vocabulary - Family words
  { id: 'v4_1', section: 'Vocabulary', task: '4 Put the letters in the correct order to make family words.', label: "1 o / n / s", type: 'unscramble', correctAnswer: "son", explanation: "O'g'il farzand.", isExample: true },
  { id: 'v4_2', section: 'Vocabulary', task: '4 Put the letters in the correct order to make family words.', label: "2 t / b / r / h / e / r / o", type: 'unscramble', correctAnswer: "brother", explanation: "Aka / uka." },
  { id: 'v4_3', section: 'Vocabulary', task: '4 Put the letters in the correct order to make family words.', label: "3 e / i / f / w", type: 'unscramble', correctAnswer: "wife", explanation: "Rafika." },
  { id: 'v4_4', section: 'Vocabulary', task: '4 Put the letters in the correct order to make family words.', label: "4 h / a / u / d / t / e / g / r", type: 'unscramble', correctAnswer: "daughter", explanation: "Qiz farzand." },
  { id: 'v4_5', section: 'Vocabulary', task: '4 Put the letters in the correct order to make family words.', label: "5 d / u / h / b / s / a / n", type: 'unscramble', correctAnswer: "husband", explanation: "Turmush o'rtoq (er)." },
  { id: 'v4_6', section: 'Vocabulary', task: '4 Put the letters in the correct order to make family words.', label: "6 t / o / h / t / e / m", type: 'unscramble', correctAnswer: "mother", explanation: "Ona." },
  { id: 'v4_7', section: 'Vocabulary', task: '4 Put the letters in the correct order to make family words.', label: "7 r / s / i / e / s / t", type: 'unscramble', correctAnswer: "sister", explanation: "Opa / singil." },
  { id: 'v4_8', section: 'Vocabulary', task: '4 Put the letters in the correct order to make family words.', label: "8 a / f / r / h / t / e", type: 'unscramble', correctAnswer: "father", explanation: "Ota." },

  // SECTION 5: Vocabulary - Match object words
  { id: 'v5_1', section: 'Vocabulary', task: '5 Match 1–8 with a–h to make object words.', label: "1 ta + [blank]", type: 'choice', options: ['ble', 'ir', 'one', 'sk', 'to', 'ock', 'puter', 'ey'], correctAnswer: 'ble', explanation: "Table - Stol.", isExample: true },
  { id: 'v5_2', section: 'Vocabulary', task: '5 Match 1–8 with a–h to make object words.', label: "2 cha + [blank]", type: 'choice', options: ['ble', 'ir', 'one', 'sk', 'to', 'ock', 'puter', 'ey'], correctAnswer: 'ir', explanation: "Chair - Stul." },
  { id: 'v5_3', section: 'Vocabulary', task: '5 Match 1–8 with a–h to make object words.', label: "3 ph + [blank]", type: 'choice', options: ['ble', 'ir', 'one', 'sk', 'to', 'ock', 'puter', 'ey'], correctAnswer: 'one', explanation: "Phone - Telefon." },
  { id: 'v5_4', section: 'Vocabulary', task: '5 Match 1–8 with a–h to make object words.', label: "4 de + [blank]", type: 'choice', options: ['ble', 'ir', 'one', 'sk', 'to', 'ock', 'puter', 'ey'], correctAnswer: 'sk', explanation: "Desk - Parta / Stol." },
  { id: 'v5_5', section: 'Vocabulary', task: '5 Match 1–8 with a–h to make object words.', label: "5 pho + [blank]", type: 'choice', options: ['ble', 'ir', 'one', 'sk', 'to', 'ock', 'puter', 'ey'], correctAnswer: 'to', explanation: "Photo - Rasm." },
  { id: 'v5_6', section: 'Vocabulary', task: '5 Match 1–8 with a–h to make object words.', label: "6 cl + [blank]", type: 'choice', options: ['ble', 'ir', 'one', 'sk', 'to', 'ock', 'puter', 'ey'], correctAnswer: 'ock', explanation: "Clock - Soat." },
  { id: 'v5_7', section: 'Vocabulary', task: '5 Match 1–8 with a–h to make object words.', label: "7 com + [blank]", type: 'choice', options: ['ble', 'ir', 'one', 'sk', 'to', 'ock', 'puter', 'ey'], correctAnswer: 'puter', explanation: "Computer - Kompyuter." },
  { id: 'v5_8', section: 'Vocabulary', task: '5 Match 1–8 with a–h to make object words.', label: "8 k + [blank]", type: 'choice', options: ['ble', 'ir', 'one', 'sk', 'to', 'ock', 'puter', 'ey'], correctAnswer: 'ey', explanation: "Key - Kalit." },

  // SECTION 6: Vocabulary - Numbers
  { id: 'v6_1', section: 'Vocabulary', task: '6 Choose the correct words for the numbers or correct numbers for words.', label: "1 12 = [blank]", type: 'choice', options: ['two', 'twelve', 'twenty'], correctAnswer: 'twelve', explanation: "12 - twelve." },
  { id: 'v6_2', section: 'Vocabulary', task: '6 Choose the correct words for the numbers or correct numbers for words.', label: "2 eleven = [blank]", type: 'choice', options: ['11', '21', '71'], correctAnswer: '11', explanation: "Eleven - 11." },
  { id: 'v6_3', section: 'Vocabulary', task: '6 Choose the correct words for the numbers or correct numbers for words.', label: "3 90 = [blank]", type: 'choice', options: ['nine', 'nineteen', 'ninety'], correctAnswer: 'ninety', explanation: "90 - ninety." },
  { id: 'v6_4', section: 'Vocabulary', task: '6 Choose the correct words for the numbers or correct numbers for words.', label: "4 eighty = [blank]", type: 'choice', options: ['8', '18', '80'], correctAnswer: '80', explanation: "Eighty - 80." },
  { id: 'v6_5', section: 'Vocabulary', task: '6 Choose the correct words for the numbers or correct numbers for words.', label: "5 twenty = [blank]", type: 'choice', options: ['12', '20', '22'], correctAnswer: '20', explanation: "Twenty - 20." },
  { id: 'v6_6', section: 'Vocabulary', task: '6 Choose the correct words for the numbers or correct numbers for words.', label: "6 17 = [blank]", type: 'choice', options: ['sixteen', 'seventeen', 'seventy'], correctAnswer: 'seventeen', explanation: "17 - seventeen." },
  { id: 'v6_7', section: 'Vocabulary', task: '6 Choose the correct words for the numbers or correct numbers for words.', label: "7 fourteen = [blank]", type: 'choice', options: ['14', '40', '44'], correctAnswer: '14', explanation: "Fourteen - 14." },

  // SECTION 7: Function - Shop Conversation
  { id: 'f7_1', section: 'Function', task: '7 Complete the conversations with words in the box.', label: "1 C: How [blank] is this chair?", type: 'box-fill', options: ['Can', 'Cash', 'change', "Here’s", 'It’s', 'much', 'please', 'that', 'They’re', 'This', 'those'], correctAnswer: 'much', explanation: "How much - narxi qancha?", isExample: true },
  { id: 'f7_2', section: 'Function', task: '7 Complete the conversations with words in the box.', label: "2 SA: [blank] £49.99.", type: 'box-fill', options: ['Can', 'Cash', 'change', "Here’s", 'It’s', 'much', 'please', 'that', 'They’re', 'This', 'those'], correctAnswer: "It’s", explanation: "Uning narxi: It is (It's)." },
  { id: 'f7_3', section: 'Function', task: '7 Complete the conversations with words in the box.', label: "3 C: How much is [blank]?", type: 'box-fill', options: ['Can', 'Cash', 'change', "Here’s", 'It’s', 'much', 'please', 'that', 'They’re', 'This', 'those'], correctAnswer: 'that', explanation: "Anavi qancha?" },
  { id: 'f7_4', section: 'Function', task: '7 Complete the conversations with words in the box.', label: "4 SA: [blank] is £12.99.", type: 'box-fill', options: ['Can', 'Cash', 'change', "Here’s", 'It’s', 'much', 'please', 'that', 'They’re', 'This', 'those'], correctAnswer: 'This', explanation: "Mana bu 12.99" },
  { id: 'f7_5', section: 'Function', task: '7 Complete the conversations with words in the box.', label: "5 C: How much are [blank] pens?", type: 'box-fill', options: ['Can', 'Cash', 'change', "Here’s", 'It’s', 'much', 'please', 'that', 'They’re', 'This', 'those'], correctAnswer: 'those', explanation: "Uzoqdagi ruchkalar - those." },
  { id: 'f7_6', section: 'Function', task: '7 Complete the conversations with words in the box.', label: "6 SA: [blank] £3.99.", type: 'box-fill', options: ['Can', 'Cash', 'change', "Here’s", 'It’s', 'much', 'please', 'that', 'They’re', 'This', 'those'], correctAnswer: "They’re", explanation: "Ular 3.99 turadi: They are (They're)." },
  { id: 'f7_7', section: 'Function', task: '7 Complete the conversations with words in the box.', label: "7 SA: [blank] or card?", type: 'box-fill', options: ['Can', 'Cash', 'change', "Here’s", 'It’s', 'much', 'please', 'that', 'They’re', 'This', 'those'], correctAnswer: 'Cash', explanation: "Naqd pul yoki karta?" },
  { id: 'f7_8', section: 'Function', task: '7 Complete the conversations with words in the box.', label: "8 C: [blank] I pay by card?", type: 'box-fill', options: ['Can', 'Cash', 'change', "Here’s", 'It’s', 'much', 'please', 'that', 'They’re', 'This', 'those'], correctAnswer: 'Can', explanation: "Karta bilan to'lay olamanmi? - Can I...?" },
  { id: 'f7_9', section: 'Function', task: '7 Complete the conversations with words in the box.', label: "9 SA: Here’s your [blank].", type: 'box-fill', options: ['Can', 'Cash', 'change', "Here’s", 'It’s', 'much', 'please', 'that', 'They’re', 'This', 'those'], correctAnswer: 'change', explanation: "Mana sizning qaytimingiz (qolgan pul)." },
  { id: 'f7_10', section: 'Function', task: '7 Complete the conversations with words in the box.', label: "10 SA: That’s £27.99, [blank].", type: 'box-fill', options: ['Can', 'Cash', 'change', "Here’s", 'It’s', 'much', 'please', 'that', 'They’re', 'This', 'those'], correctAnswer: 'please', explanation: "Iltimos (so'ralayotgan pul miqdori)." },
  { id: 'f7_11', section: 'Function', task: '7 Complete the conversations with words in the box.', label: "11 C: [blank] my card.", type: 'box-fill', options: ['Can', 'Cash', 'change', "Here’s", 'It’s', 'much', 'please', 'that', 'They’re', 'This', 'those'], correctAnswer: "Here’s", explanation: "Mana mening kartam: Here is (Here's)." },
];
